### PR TITLE
correct tutorial on how to install inout

### PR DESCRIPTION
**Pull request by zck**
A few changes:
1. elasticsearch requires two dashes for long command line options
2. Give the clone url that doesn't require a github login.
3. Make the inline blocks of code render as blocks of code.

### CODE REVIEW

**Comment by apatrida** [comment]
I should apply this to my fork, no pull requests have gone through here in a while, I am hoping it is not abandoned.  My fork has versions compatible with up to 1.0.0.Beta1.  I'll do the updates for 0.90.7 and 1.0.0.Beta2 now.  

I'm pretending my fork is master for now in absence of any reply, response or sign that this repo is alive.
https://github.com/bremeld/fork-elasticsearch-inout-plugin

**Comment by apatrida** [comment]
applied to the bremeld fork by hand.

**Comment by jodok** [comment]
:+1: thanks for your contribution and sorry for not processing it so far. we're in the progress of collecting the various pull requests and will process them asap!

**Comment by zck** [comment]
Closing this PR so I don't see it anymore. Certainly still merge it, but it looks like this project isn't so active.

**Pull request closed without merging**
